import { HaraRuntime } from "./evaluator.js";
import { createCanonicalRuntime } from "./canonical.js";

/**
 * Prefer the official browser runtime archive generated by hara-lang/hara.
 * The embedded evaluator remains a deliberately small development fallback so
 * the IDE, workspace and protocol stay usable without a Rust build toolchain.
 */
export async function createRuntimeHost(options = {}) {
  try {
    const runtime = await createCanonicalRuntime(options);
    return { runtime, kind: "canonical-wasm", startupDiagnostics: [] };
  } catch (error) {
    const cause = deepestCause(error);
    const message = cause && cause !== error
      ? `${error.message || error}: ${cause.message || cause}`
      : error.message || String(error);
    const startupDiagnostics = [
      `Unable to initialise canonical Hara runtime: ${message}`,
      "Using the embedded HAL evaluator; install an official Studio runtime archive for full Hara semantics"
    ];
    for (const diagnostic of startupDiagnostics) options.onDiagnostic?.(diagnostic);
    return {
      runtime: new HaraRuntime(options),
      kind: "embedded",
      startupDiagnostics
    };
  }
}

function deepestCause(error) {
  let current = error;
  const seen = new Set();
  while (current?.cause && !seen.has(current.cause)) {
    seen.add(current);
    current = current.cause;
  }
  return current;
}
