import { HaraRuntime } from "./evaluator.js";
import { CanonicalRuntimeUnavailableError, createCanonicalRuntime } from "./canonical.js";

/**
 * Prefer the official browser runtime archive generated by hara-lang/hara.
 * The embedded evaluator remains a deliberately small development fallback so
 * the IDE, workspace and protocol stay usable without a Rust build toolchain.
 */
export async function createRuntimeHost(options = {}) {
  try {
    const runtime = await createCanonicalRuntime(options);
    return { runtime, kind: "canonical-wasm" };
  } catch (error) {
    if (!(error instanceof CanonicalRuntimeUnavailableError)) {
      options.onDiagnostic?.(`Unable to initialise canonical Hara runtime: ${error.message || error}`);
    }
    options.onDiagnostic?.("Using the embedded HAL evaluator; install an official Studio runtime archive for full Hara semantics");
    return { runtime: new HaraRuntime(options), kind: "embedded" };
  }
}
